#!/bin/sh

# Install Soft Float.
# Your current working directory MUST be the one where this file resides
# DO NOT source this script.

error () {
echo "Unable to $*.  Terminating." >&2
exit 12
}

todir=../../$(uname -m)/s3fh.release
echo "Building for release in '$todir'." >&2

cd $todir
if [ $? -ne 0 ] ; then
        error "change directory to '$todir'"
fi

cmake -P cmake_install.cmake
if [ $? -ne 0 ] ; then
        error "install"
fi
